import type {
  HumanHandoffKind,
  HumanHandoffRequest,
  HumanHandoffResolution,
} from './human-handoff.types';

/**
 * DI token for the durable human-handoff row store.
 *
 * The port surface mirrors the four CRUD primitives used by
 * `HumanHandoffService`. Adapters (Postgres today; tests may add an
 * in-memory adapter) bind to this token via `useClass`.
 */
export const HUMAN_HANDOFF_STORE = Symbol('HUMAN_HANDOFF_STORE');

/** Input shape for `HumanHandoffStore.create`. The caller computes the
 *  `id` (12 lowercase hex chars from a UUID v4) so the adapter can rely
 *  on a deterministic PK that matches the public `HF-${id}` ref. */
export interface CreateHumanHandoffInput {
  id: string;
  customerId: string;
  agentId: string;
  kind: HumanHandoffKind;
  digest: HumanHandoffRequest['digest'];
}

/** Port abstraction for human-handoff row persistence. */
export interface HumanHandoffStore {
  /**
   * Insert a new handoff request. The row is created with
   * `status='pending'`, `resolution=null`, `resolved_at=null`,
   * `created_at=now()`. The full created row (with `createdAt`) is
   * returned.
   *
   * Adapters MUST treat duplicate `id` as a hard error (the `id` is
   * generated by the service with `crypto.randomUUID().replace(/-/g,'')`).
   */
  create(input: CreateHumanHandoffInput): Promise<HumanHandoffRequest>;

  /**
   * Return the row by internal id (12 lowercase hex chars). Returns
   * `null` when not found.
   */
  findById(id: string): Promise<HumanHandoffRequest | null>;

  /**
   * Return the row by public ref (`HF-${id}`). Adapters MUST accept
   * refs with or without the `HF-` prefix and tolerate case. Returns
   * `null` when not found.
   */
  findByRef(ref: string): Promise<HumanHandoffRequest | null>;

  /**
   * Return the newest pending row for the given agent, or `null`. The
   * fallback path of `resolveReply(tokenless)` relies on this contract:
   * at most one pending request per agent at a time (ADR-24).
   */
  findLatestPendingForAgent(
    agentId: string,
  ): Promise<HumanHandoffRequest | null>;

  /**
   * Compare-and-set transition of a pending request to resolved. Sets
   * `status='resolved'`, `resolution`, `resolved_at=now()` only when the
   * row is still `status='pending'`. Returns the updated row; returns
   * `null` when no pending row with the given id exists — an unknown id
   * OR an already-resolved row. A repeated/concurrent resolve therefore
   * never overwrites a recorded decision (the caller logs and asks for
   * a ref).
   */
  resolve(
    id: string,
    resolution: HumanHandoffResolution,
  ): Promise<HumanHandoffRequest | null>;
}
